builders:
  strata:
    import: "package:strata_builder/strata_builder.dart"
    builder_factories: ["strataBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: source
