// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by bin/generate_migrations.dart

import 'package:strata_sqlite/strata_sqlite.dart';

/// Auto-generated migrations from the migrations/ directory.
class Migrations {
  static List<SqlMigration> get all => [
        SqlMigration(
          version: 20241117100000,
          name: 'create_users_table',
          upStatements: [
            'CREATE TABLE users (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  email TEXT NOT NULL UNIQUE,\n  created_at INTEGER NOT NULL\n);',
            'CREATE INDEX idx_users_email ON users(email);',
          ],
          downStatements: [
            'DROP INDEX IF EXISTS idx_users_email;',
            'DROP TABLE IF EXISTS users;',
          ],
        ),
        SqlMigration(
          version: 20241117101000,
          name: 'create_todos_table',
          upStatements: [
            'CREATE TABLE todos (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  user_id INTEGER NOT NULL,\n  title TEXT NOT NULL,\n  description TEXT,\n  completed INTEGER NOT NULL DEFAULT 0,\n  due_date INTEGER,\n  created_at INTEGER NOT NULL,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE\n);',
            'CREATE INDEX idx_todos_user_id ON todos(user_id);',
            'CREATE INDEX idx_todos_completed ON todos(completed);',
            'CREATE INDEX idx_todos_due_date ON todos(due_date);',
          ],
          downStatements: [
            'DROP INDEX IF EXISTS idx_todos_due_date;',
            'DROP INDEX IF EXISTS idx_todos_completed;',
            'DROP INDEX IF EXISTS idx_todos_user_id;',
            'DROP TABLE IF EXISTS todos;',
          ],
        ),
      ];
}
